### ISSUE TITLE
Iron Banner header not properly tracking Iron Banner games now, probably due to the game mode switching to Clash

### ISSUE THREAD

**Issue by Mulchman** [guardiangg/http-client#15]
Now that Iron Banner is Clash, the tracking of Iron Banner games seems to be bugged/broken.  In this screenshot, the Rusted Lands game that shows up under **All** is an Iron Banner game from today (November 18, 2015). However, when I click the **Iron Banner** header, it shows that my last Iron Banner game was a month ago.

![example](http://i.imgur.com/bUS3ogj.png)

**Comment by spiffyjr** [comment]
Iron Banner is being tracked by Bungie as Clash in their data so we can't do much about it. See #14 as well.

Sorry about that.

**Comment by Mulchman** [comment]
Thanks for the update. After making this issue, later in the day I noticed a pop-up on destinytracker saying Iron Banner games were getting tagged as Clash on Bungie's end, and I thought to come back here and update, but it was too late.

**Comment by ItsCalebJones** [comment]
Just a note I brought this to Bungies attention, its in there hands now.

https://www.bungie.net/en/Forum/Post/174419056/0/0/1
