### ISSUE TITLE
Public API?

### ISSUE THREAD

**Issue by syropian** [guardiangg/http-client#21]
Is there any plans to open up the API for third party access?

**Comment by mdurrant** [comment]
The API can be freely used at the moment, you can safely use it unless the volume of requests borders on abusive (at which point your requests may be rate limited or blacklisted). It's on our internal road map to get documentation & app registration at some point.

We'd like to flesh it out for third party usage too, so if you have any particular requests, open a ticket and we'll see if we can do it.
