### ISSUE TITLE
Team Elo

### ISSUE THREAD

**Issue by koush** [guardiangg/http-client#22]
From what I gather with the current system, a team elo is calculated as an average of all three players. Then the Team Elo is used to calculate how many points are gained/lost per player upon conclusion of the match. Each player on the team is awarded/penalized the same amount.

If three players in a team start with different Elos, say 1400, 1700, and 1900. Mathematically, if these players only play with each other, as the number of games they play together approaches infinity, their Elos should converge to the same value. However, with the current setup, they will retain their relative Elo point difference.
Ie, if the aforementioned team gained 200 points after a hundred thousand games, they would still be 1600, 1900, and 2100. I think their Elos should probably converge at 1866, the average.

Here's a reddit thread with some possible solutions and thoughts from a few years ago:
https://www.reddit.com/r/math/comments/1j3zpe/implementing_elo_for_team_based_games

My initial thought is to do per 9 elo calculations at the end of a match. And perhaps award a 1/3 of the points per calculation:

Alpha1 v Bravo1
Alpha1 v Bravo2
Alpha1 v Bravo3
Alpha2 v Bravo1
...
Alpha3 v Bravo3

Anyways, great site, very well done! Just figured I'd throw some suggestions into the wind about how I think the team based elo could be improved.

**Comment by spiffyjr** [comment]
We're working on quite a few changes to the Elo formula as well as new features to go with it. This isn't an easy problem to solve because converging on an average Elo comes with it's own share of issues. 

Hopefully the tweaks we make will help a bit.  I know people are carrying to increase their Elo but if they're good enough to do single or double carries they probably deserve their spot at the top of the boards, right?

**Comment by ItsCalebJones** [comment]
>   if they're good enough to do single or double carries they probably deserve their spot at the top of the boards

I'm not sure if I agree with that. Interested to hear what the community might think though. Also shoutout to seeing @koush here.

**Comment by koush** [comment]
@spiffyjr 
I agree that people doing carries should get rewarded ELO. Which brings me to my next point...

The other flaw with the current ELO system is that people are gaming the system it via account recovery. Have your very skilled carry partners get on low ELO accounts, and use them to boost your ELO.

I know for certain that one of the top 5 Xbox players does this. Defeats the intent of the system. Using high ELO players on low ELO accounts removes any personal stake to your ELO, since the team ELO is still quite low. Decoupling your ELO gain/loss from that of your teammates would resolve this, as well as fix my original point.

Another thought I had, though this would result in a exponential number of teams, is to do actual unique team ELOs for team settings. (Probably don't want this for 6v6 heh)
