### ISSUE TITLE
looking up stats causes contacting destiny servers

### ISSUE THREAD

**Issue by lxghtless** [guardiangg/http-client#23]
this happens every time I check my stats for the first time in a few hours. literally the second I look it up, the "contacting destiny servers" error message pops up. At first I thought it was a coincidence, but then it happens EVERY time over the last 2 months. I should obviously just stop looking up stats while I'm playing, but still...

**Comment by spiffyjr** [comment]
What's your gamer tag and platform?

**Edit** Wait, you think our website has something to do with your Destiny connection? This isn't happening because of us - I don't know what else to tell you.

**Comment by lxghtless** [comment]
It must just be a coincidence.... that happens over and over.

I wonder if it's more of an issue on Bungie's end, where pulling stats during game play can conflict with the users current game session. I understand the "I don't know what else to tell you." response, but it could be second hand related to any site pulling statistical data from Bungie... not a whole lot you could do about that if it's the case.

**Comment by lxghtless** [comment]
@spiffyjr - I popped open fiddler and refreshed that page... it records ~130 individual requests... maybe it's just suffocating my internet connection and destiny detects that. maybe consolidating the calls through a gateway call of some sort would help.. not sure. it's not you're fault (e.g. I could just pay for fiber business class internet or something)... but I think there's an opportunity to reduce all those calls.
