### ISSUE TITLE
License

### ISSUE THREAD

**Issue by wpp** [guardiangg/http-client#26]
Hi,

First off: Thank you for the hard work on guardian.gg! My friends and I are regularly visiting the site and appreciate all the effort that went into this project.

I believe I've seen usage of some of your assets (font) on other sites and was wondering [what license this project is released under](http://blog.codinghorror.com/pick-a-license-any-license/)?
Is that something you still have to make a decision about?

Hopefully I didn't miss it.

**Comment by mdurrant** [comment]
Sorry for the delay in responding. Affixing a license on the site hasn't been a priority for us, but I will say, as the author of the font, you can use that asset under MIT. If you have any other specific requests for other assets in the repo just let me know.

**Comment by wpp** [comment]
No worries, glad to hear that and thanks for your reply.
