### ISSUE TITLE
Occasional whitepage onload

### ISSUE THREAD

**Issue by iBotPeaches** [guardiangg/http-client#30]
Every once in awhile when I visit the site, I'm staring at a blank white page until I refresh.

Seems to be race condition for something, as the error I get is different when it occurs. It does appear that when this problem occurs, the redirect to my locale (`en`) never happens.

```
TypeError: window.gggTips is undefined
Uncaught TypeError: Cannot read property 'locale' of undefined
```

**Comment by mdurrant** [comment]
Fixed by f9013c6014e714e2795a0b2d53d2b9a9bfe523b7
